= Kumoru

image:https://img.shields.io/badge/vert.x-3.9.0-purple.svg[link="https://vertx.io"]

A minimal implementation of Nexus repository to practice Vert.x

== Features

.Mirrors the following repositories:
* [x] Maven 2.
* [x] JCenter.
* [x] Jitpack.

.Snapshots
* [x] Enable snapshot repositories of above mirrors.

.Publishing artifacts
* [x] Publish artifacts to Kumoru.

.HTTP methods supported
* [x] GET
* [x] PUT

== Pre-Requisites

1. Java 11
2. Docker

== Running the server

To run your application:
```
docker run -p 8888:8888 -v /tmp/repo:/srv/repo rishabh9/kumoru
```

> `/tmp/repo` can be replaced with any path of your choice.
> This is the location where the artifacts will be downloaded on the host machine.

To enable access logs, set the environment variable `KUMORU_ACCESS_LOG=true` as:
```
docker run -e KUMORU_ACCESS_LOG=true -p 8888:8888 -v /tmp/repo:/srv/repo rishabh9/kumoru
```

> All logs are written to the `STDOUT`.

== Configuring Maven

.Mirroring
Edit Maven's `settings.xml` and add a `<mirror>`:

```
  <mirrors>
    <mirror>
      <id>kumoru</id>
      <mirrorOf>*</mirrorOf>
      <name>Kumoru - A minimal Nexus repository</name>
      <url>http://localhost:8888</url>
    </mirror>

  </mirrors>
```

.Publishing

In your `pom.xml` add

```
  <distributionManagement>
    <repository>
      <id>kumoru</id>
      <name>Kumoru - A minimal Nexus repository</name>
      <url>http://localhost:8888</url>
    </repository>
  </distributionManagement>
```

== Configuring Gradle

.Mirroring

Add to you `build.gradle`

```
repositories {
  maven {
    url: "http://localhost:8080"
  }
}
```

.Publishing

Add to your `build.gradle`

```
publishing {
  repositories {
    maven {
      url: "http://localhost:8080"
    }
  }
}
```

== Building the code

To build your application:
```
./gradlew clean build
```

To package your application into Docker container:
```
./gradlew jibDockerBuild
```
